create table public.users (
    id          bigint generated by default as identity primary key,
    username    varchar(50) not null unique,
    email       varchar(255) not null unique,
    password    varchar(255) not null,
    created_at  timestamptz default now(),
    updated_at  timestamptz default now()
);
