create table public.workflows (
    id          bigint generated by default as identity primary key,
    user_id     bigint references public.users(id) on delete cascade,
    name        varchar(100) not null,
    description text,
    definition  jsonb not null,
    created_at  timestamptz default now(),
    updated_at  timestamptz default now()
);
